kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
