apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: tools-ubuntu-privileged
  name: tools-ubuntu-privileged
  namespace: linux-container
spec:
  failedBuildsHistoryLimit: 2
  successfulBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: 'tools-ubuntu-privileged:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: tools-container/docker
    git:
      uri: 'https://github.com/avoigtma/openshift-misc.git'
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile-ubuntu-privileged.docker
      from:
        kind: ImageStreamTag
        name: 'ubuntu:latest'
        namespace: openshift
      noCache: true
    type: Docker
  triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: 'ubuntu:latest'
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
