apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: tools
  name: tools
  namespace: linux-container
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'tools:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: docker
    git:
      uri: 'https://github.com/avoigtma/openshift-certmonger.git'
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile-tools.docker
      from:
        kind: ImageStreamTag
        name: 'centos:latest'
        namespace: openshift
      noCache: true
    type: Docker
  triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: 'centos:latest'
          namespace: openshift
      type: ImageChange
    - type: ConfigChange
