kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: tools-privileged
  namespace: linux-container
  labels:
    app: tools-privileged
    app.kubernetes.io/component: tools-privileged
    app.kubernetes.io/instance: tools-privileged
    app.kubernetes.io/name: tools-privileged
    app.kubernetes.io/part-of: tools-privileged-app
    app.openshift.io/runtime: tools-privileged
    app.openshift.io/runtime-namespace: linux-container
    app.openshift.io/runtime-version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tools-privileged
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: tools-privileged
        deploymentconfig: tools-privileged
    spec:
      containers:
        - name: tools-privileged
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              while (true); do date +%F--%H-%M-%S; echo "please use the container terminal ... "; echo ""; sleep 60; done
          image: >-
            image-registry.openshift-image-registry.svc:5000/linux-container/tools-privileged:latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 1000
      serviceAccountName: privileged-sa
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
