apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: iperf
  name: iperf
  namespace: iperf
spec:
  failedBuildsHistoryLimit: 2
  successfulBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: 'iperf:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: iperf/docker
    git:
      uri: 'https://github.com/avoigtma/openshift-misc.git'
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile-iperf.docker
      from:
        kind: ImageStreamTag
        name: 'ubi9-ubi:latest'
        namespace: openshift
      noCache: true
      volumes:
      - name: etc-pki-entitlement
        mounts:
        - destinationPath: /etc/pki/entitlement
        source:
          type: Secret
          secret:
            secretName: etc-pki-entitlement
    type: Docker
  triggers:
    - type: ConfigChange
