kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: iperf-client
  namespace: iperf
  labels:
    app: iperf
    app.kubernetes.io/component: iperf
    app.kubernetes.io/instance: iperf-client
    app.kubernetes.io/name: iperf-client
    app.kubernetes.io/part-of: iperf-app
    app.openshift.io/runtime: iperf
    app.openshift.io/runtime-namespace: iperf
    app.openshift.io/runtime-version: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iperf
        deploymentconfig: iperf-client
    spec:
      nodeName: compute-0
      containers:
        - name: iperf
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              while (true); do date +%F--%H-%M-%S; echo "please use the container terminal ... "; echo ""; sleep 60; done
          image: >-
            quay.io/avoigtma/netperf:latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
