apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: iperf
  namespace: iperf
  labels:
    app: iperf
    app.kubernetes.io/component: iperf
    app.kubernetes.io/instance: iperf
    app.kubernetes.io/name: iperf
    app.kubernetes.io/part-of: iperf-app
    app.openshift.io/runtime: iperf
    app.openshift.io/runtime-namespace: iperf
    app.openshift.io/runtime-version: latest
spec: {}
