apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: perftools
    app.kubernetes.io/component: perftools
    app.kubernetes.io/instance: perftools
    app.kubernetes.io/name: perftools
    app.kubernetes.io/part-of: perftools-app
    app.openshift.io/runtime: perftools
    app.openshift.io/runtime-namespace: perftools
    app.openshift.io/runtime-version: latest
  name: privileged-binding
  namespace: perftools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-access
subjects:
- kind: ServiceAccount
  name: privileged-sa
  namespace: perftools