kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cronjob-etcd-backup
  labels:
    app.kubernetes.io/name: cronjob-etcd-backup
subjects:
  - kind: ServiceAccount
    name: cronjob-etcd-backup
    namespace: etcd-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cronjob-etcd-backup
