apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: iperf
    app.kubernetes.io/component: iperf
    app.kubernetes.io/instance: iperf
    app.kubernetes.io/name: iperf
    app.kubernetes.io/part-of: iperf-app
    app.openshift.io/runtime: iperf
    app.openshift.io/runtime-namespace: iperf
    app.openshift.io/runtime-version: latest
  name: privileged-binding
  namespace: iperf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-access
subjects:
- kind: ServiceAccount
  name: privileged-sa
  namespace: iperf