apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: perftools
  namespace: perftools
  labels:
    app: perftools
    app.kubernetes.io/component: perftools
    app.kubernetes.io/instance: perftools
    app.kubernetes.io/name: perftools
    app.kubernetes.io/part-of: perftools-app
    app.openshift.io/runtime: perftools
    app.openshift.io/runtime-namespace: perftools
    app.openshift.io/runtime-version: latest
spec: {}
