kind: Job
apiVersion: batch/v1
metadata:
  annotations:
  name: fiotest
  namespace: perftools
  labels:
    app: perftools
    app.kubernetes.io/component: perftools
    app.kubernetes.io/instance: perftools
    app.kubernetes.io/name: perftools
    app.kubernetes.io/part-of: perftools-app
    app.openshift.io/runtime: perftools
    app.openshift.io/runtime-namespace: perftools
    app.openshift.io/runtime-version: latest
spec:
  backoffLimit: 1
  completions: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: perftools
        deploymentconfig: perftools
    spec:
      volumes:
        - name: fiotest
          persistentVolumeClaim:
            claimName: fiotest-job
      containers:
        - name: perftools
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              echo "Running FIO test script and creating ConfigMap with results"
              TIMESTAMP=$(date "+%Y-%m-%d--%H-%M")
              /scripts/fiotests.sh $TIMESTAMP
              oc create cm -n perftools fio-results-$TIMESTAMP --from-file=$FIOBASEDIR/$FIOOUTDIR/$TIMESTAMP
          env:
            - name: FIOBASEDIR
              value: /fiotest
            - name: FIOOUTDIR
              value: outputs
          image: >-
            quay.io/avoigtma/perftools:latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          volumeMounts:
            - name: fiotest
              mountPath: /fiotest
      restartPolicy: Never
      serviceAccountName: perftools-sa
