kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fiotest
  namespace: perftools
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
